on: [push, pull_request]

name: Plugin builds

jobs:
    plugin:
        name: Build plugin
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x

            - name: Setup Bomb Rush Cyberfunk dependencies
              run: ./gha.ps1

            - name: Build
              run: ./build.ps1
              env:
                  BRCPath: ${{ github.workspace }}/local/BombRushCyberfunk

            - name: Upload plugin artifact
              uses: actions/upload-artifact@v3
              with:
                  name: plugin
                  path: ./SlopCrew.Plugin/bin/Release/net462

            - name: Upload Thunderstore artifact
              uses: actions/upload-artifact@v3
              with:
                  name: thunderstore
                  path: ./thunderstore
