on: [push, pull_request]

name: Server builds

jobs:
    server:
        name: Build server
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Install .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build SlopCrew.Server --configuration Release --no-restore

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: server-windows
                  path: ./SlopCrew.Server/bin/Release/net7.0
